#Relatorio de uma pessoa aleatoria
nome = input('Digite seu nome: ')
idade = input('Digite sua idade: ')
cpf = input('Digite seu CPF: ')
endereco = input('Digite seu endereço: ')
altura = input('Digite sua altura: ')
telefone = input('Digite seu telefone: ')

print('\nRELATÓRIO\n')
print('Nome:', nome)
print('Idade: ', idade, 'anos')
print('CPF:', cpf)
print ('Endereço:', endereco)
print('Altura:', altura, 'metros')
print('Telefone:', telefone)
